SimpleLang=_{SOI ~  meaningless_space ~ (expression ~ meaningless_space)* ~ EOI}
expression = _{list | string}
string = {(!(space | left_bracket | right_bracket) ~ ANY)+}
list = {left_bracket ~ meaningless_space ~ expression ~ (space ~ expression)+ ~ meaningless_space ~ right_bracket}

left_bracket = _{"("}
right_bracket = _{")"}


space= _{space_symbol+}
meaningless_space = _{space_symbol*}
space_symbol = _{" " | "\n" | "\t"|"\r"}

